// NEW: presety skal (durowa, molowa, pentatoniki + parę modalnych)
export const SCALE_PRESETS = {
  'Major (ionian)': [
    { semis: 0,  deg: '1' },
    { semis: 2,  deg: '2' },
    { semis: 4,  deg: '3' },
    { semis: 5,  deg: '4' },
    { semis: 7,  deg: '5' },
    { semis: 9,  deg: '6' },
    { semis: 11, deg: '7' },
  ],
  'Natural minor (aeolian)': [
    { semis: 0,  deg: '1' },
    { semis: 2,  deg: '2' },
    { semis: 3,  deg: 'b3' },
    { semis: 5,  deg: '4' },
    { semis: 7,  deg: '5' },
    { semis: 8,  deg: 'b6' },
    { semis: 10, deg: 'b7' },
  ],
  'Harmonic minor': [
    { semis: 0,  deg: '1' },
    { semis: 2,  deg: '2' },
    { semis: 3,  deg: 'b3' },
    { semis: 5,  deg: '4' },
    { semis: 7,  deg: '5' },
    { semis: 8,  deg: 'b6' },
    { semis: 11, deg: '7' },
  ],
  'Melodic minor (asc.)': [
    { semis: 0,  deg: '1' },
    { semis: 2,  deg: '2' },
    { semis: 3,  deg: 'b3' },
    { semis: 5,  deg: '4' },
    { semis: 7,  deg: '5' },
    { semis: 9,  deg: '6' },
    { semis: 11, deg: '7' },
  ],
  'Major pentatonic': [
    { semis: 0,  deg: '1' },
    { semis: 2,  deg: '2' },
    { semis: 4,  deg: '3' },
    { semis: 7,  deg: '5' },
    { semis: 9,  deg: '6' },
  ],
  'Minor pentatonic': [
    { semis: 0,  deg: '1' },
    { semis: 3,  deg: 'b3' },
    { semis: 5,  deg: '4' },
    { semis: 7,  deg: '5' },
    { semis: 10, deg: 'b7' },
  ],
  'Dorian': [
    { semis: 0,  deg: '1' },
    { semis: 2,  deg: '2' },
    { semis: 3,  deg: 'b3' },
    { semis: 5,  deg: '4' },
    { semis: 7,  deg: '5' },
    { semis: 9,  deg: '6' },
    { semis: 10, deg: 'b7' },
  ],
  'Mixolydian': [
    { semis: 0,  deg: '1' },
    { semis: 2,  deg: '2' },
    { semis: 4,  deg: '3' },
    { semis: 5,  deg: '4' },
    { semis: 7,  deg: '5' },
    { semis: 9,  deg: '6' },
    { semis: 10, deg: 'b7' },
  ],
} as const
